# scaffolder.py
import json
import os
import re
from pathlib import Path
from typing import Dict, List
from models import ArchitecturePlan


class ProjectScaffolder:
    """
    Takes the AI's architecture plan and creates actual project files.
    This is what makes our system unique — we generate real code, not just text.
    """

    def __init__(self, plan: ArchitecturePlan, project_name: str = "my-app"):
        self.plan = plan
        self.project_name = project_name.replace(" ", "-").lower()
        self.base_path = Path(f"./generated_projects/{self.project_name}")

    def scaffold(self) -> Dict[str, str]:
        """
        Create the complete project structure.
        Returns: Dictionary of file paths and their content
        """
        # 1. Create the base folder structure
        self._create_folders()

        # 2. Generate starter files
        files = {
            "package.json": self._generate_package_json(),
            ".env.example": self._generate_env_example(),
            "Dockerfile": self._generate_dockerfile(),
            "README.md": self._generate_readme(),
        }

        # 3. Write all files to disk
        for filename, content in files.items():
            self._write_file(filename, content)

        # 4. Create starter code based on frontend/backend
        if "Next.js" in self.plan.frontend:
            self._generate_nextjs_starter()

        if "Express" in self.plan.backend or "Node" in self.plan.backend:
            self._generate_express_starter()

        # 5. Return what was generated
        return {
            "path": str(self.base_path),
            "folders_created": self._get_folder_list(),
            "files_created": list(files.keys()) + ["app/page.jsx", "index.js"],
        }

    def _create_folders(self):
        """Create the folder structure from the AI's recommendation."""
        structure = self.plan.folder_structure_hint

        folders = re.findall(r"\{([^}]+)\}", structure)

        if folders:
            base = structure.split("{")[0].strip("/")
            for folder in folders[0].split(","):
                path = self.base_path / base / folder.strip()
                path.mkdir(parents=True, exist_ok=True)
        else:
            default_folders = ["src/components", "src/pages", "src/api", "src/utils"]
            for folder in default_folders:
                (self.base_path / folder).mkdir(parents=True, exist_ok=True)

    def _generate_package_json(self) -> str:
        """Generate package.json based on the tech stack."""
        dependencies = {
            "express": "^4.18.0",
            "cors": "^2.8.5",
            "dotenv": "^16.0.0",
            "jsonwebtoken": "^9.0.0",
            "bcrypt": "^5.1.0",
        }

        if "Next.js" in self.plan.frontend:
            dependencies["next"] = "^14.0.0"
            dependencies["react"] = "^18.0.0"
            dependencies["react-dom"] = "^18.0.0"

        if "PostgreSQL" in self.plan.database:
            dependencies["pg"] = "^8.11.0"
            dependencies["prisma"] = "^5.0.0"

        if "Redis" in str(self.plan.caching):
            dependencies["redis"] = "^4.6.0"

        package_json = {
            "name": self.project_name,
            "version": "1.0.0",
            "description": f"{self.plan.project_type} - Generated by AI Architect",
            "main": "index.js",
            "scripts": {"start": "node index.js", "dev": "nodemon index.js"},
            "dependencies": dependencies,
            "devDependencies": {"nodemon": "^3.0.0"},
        }

        return json.dumps(package_json, indent=2)

    def _generate_env_example(self) -> str:
        """Generate .env.example with required environment variables."""
        env_vars = [
            "# Environment Variables",
            "PORT=3000",
            "NODE_ENV=development",
            "JWT_SECRET=your-secret-key-here",
            f"DATABASE_URL=postgresql://user:password@localhost:5432/{self.project_name}",
        ]

        if "Redis" in str(self.plan.caching):
            env_vars.append("REDIS_URL=redis://localhost:6379")

        return "\n".join(env_vars)

    def _generate_dockerfile(self) -> str:
        """Generate a Dockerfile for containerization."""
        return f"""# Generated Dockerfile for {self.project_name}
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
"""

    def _generate_readme(self) -> str:
        """Generate README.md with project overview."""
        caching_info = "\n- Redis" if "Redis" in str(self.plan.caching) else ""

        task_list = ""
        for task in self.plan.first_phase_tasks:
            task_list += f"- {task}\n"

        # Build the README using string concatenation (avoids f-string backtick issues)
        readme = f"# {self.plan.project_type} - {self.project_name}\n\n"
        readme += "## Overview\n"
        readme += (
            "This project was automatically generated by the AI Software Architect.\n\n"
        )
        readme += "## Architecture\n"
        readme += f"- **Frontend**: {self.plan.frontend}\n"
        readme += f"- **Backend**: {self.plan.backend}\n"
        readme += f"- **Database**: {self.plan.database}\n"
        readme += f"- **Caching**: {self.plan.caching or 'None'}\n\n"
        readme += "## Getting Started\n\n"
        readme += "### Prerequisites\n"
        readme += "- Node.js (v18+)\n"
        readme += f"- {self.plan.database}{caching_info}\n\n"
        readme += "### Installation\n"
        readme += "```bash\n"
        readme += "npm install\n"
        readme += "```\n\n"
        readme += "### Environment Setup\n"
        readme += "```bash\n"
        readme += "cp .env.example .env\n"
        readme += "# Edit .env with your configuration\n"
        readme += "```\n\n"
        readme += "### Running the Application\n"
        readme += "```bash\n"
        readme += "npm run dev\n"
        readme += "```\n\n"
        readme += "## Project Structure\n"
        readme += "```\n"
        readme += f"{self.plan.folder_structure_hint}\n"
        readme += "```\n\n"
        readme += "## Phase 1 Tasks\n"
        readme += task_list
        readme += "\n## License\n"
        readme += "MIT\n"

        return readme

    def _write_file(self, filename: str, content: str):
        """Write content to a file in the project directory."""
        file_path = self.base_path / filename
        file_path.parent.mkdir(parents=True, exist_ok=True)
        with open(file_path, "w") as f:
            f.write(content)

    def _get_folder_list(self) -> List[str]:
        """Get list of all folders created."""
        folders = []
        for root, dirs, _ in os.walk(self.base_path):
            for dir_name in dirs:
                folders.append(str(Path(root) / dir_name))
        return folders

    def _generate_nextjs_starter(self):
        """Generate Next.js starter files."""
        task_list = ""
        for i, task in enumerate(self.plan.first_phase_tasks):
            task_list += f'<li key="task-{i}">{task}</li>\n'

        page_content = f"""// Generated by AI Architect - {self.plan.project_type}
export default function HomePage() {{
  return (
    <main className="min-h-screen p-8">
      <h1 className="text-4xl font-bold">{self.plan.project_type}</h1>
      <p className="mt-4">Welcome to your {self.plan.project_type} application.</p>
      <div className="mt-8">
        <h2 className="text-2xl font-semibold">Getting Started</h2>
        <ul className="list-disc ml-6 mt-2">
          {task_list}
        </ul>
      </div>
    </main>
  )
}}
"""
        self._write_file("app/page.jsx", page_content)

    def _generate_express_starter(self):
        """Generate Express.js starter files."""
        index_content = f"""// Generated by AI Architect - {self.plan.project_type}
const express = require('express');
const cors = require('cors');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());

// Health check
app.get('/health', (req, res) => {{
  res.json({{ status: 'ok', message: '{self.plan.project_type} is running' }});
}});

// TODO: Add your routes here
// Example: app.use('/api/courses', require('./routes/courses'));

app.listen(PORT, () => {{
  console.log(`🚀 Server running on port ${{PORT}}`);
}});
"""
        self._write_file("index.js", index_content)


# ============================================================
# THIS IS THE FUNCTION THAT main.py IMPORTS
# ============================================================
def scaffold_project(
    plan: ArchitecturePlan, project_name: str = None
) -> Dict[str, str]:
    """
    Convenience function to scaffold a project from an architecture plan.
    This is what gets called by main.py's /scaffold endpoint.
    """
    if not project_name:
        project_name = plan.project_type.replace(" ", "-")

    scaffolder = ProjectScaffolder(plan, project_name)
    return scaffolder.scaffold()


# ============================================================
# Quick test when you run: python scaffolder.py
# ============================================================
if __name__ == "__main__":
    from models import ArchitecturePlan

    test_plan = ArchitecturePlan(
        project_type="E-learning Platform",
        primary_language="JavaScript",
        frontend="Next.js 14",
        backend="Node.js with Express",
        database="PostgreSQL",
        caching="Redis",
        folder_structure_hint="src/{components,pages,styles,utils,api}",
        first_phase_tasks=[
            "Setup JWT authentication",
            "Create course CRUD API",
            "Implement video player",
        ],
    )

    result = scaffold_project(test_plan, "test-elearning")
    print("✅ Project scaffolded at:", result["path"])
    print("📁 Folders created:", result["folders_created"])
    print("📄 Files created:", result["files_created"])
